/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

/**
 *
 * @author UTILISATEUR
 */
public class FnPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public FnPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMenuPrincipal = new javax.swing.JLabel();
        btChangerObjectif = new javax.swing.JButton();
        btProfil = new javax.swing.JButton();
        lbFixeObjectifs = new javax.swing.JLabel();
        lbObjectifs = new javax.swing.JLabel();
        btDeconnexion = new javax.swing.JButton();
        btAide = new javax.swing.JButton();
        btAjoutActivite = new javax.swing.JButton();
        btRecapActivite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenuPrincipal.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        lbMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuPrincipal.setText("Menu Principal");

        btChangerObjectif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btChangerObjectif.setText("Changer Objectifs");

        btProfil.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btProfil.setText("Profil");

        lbFixeObjectifs.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbFixeObjectifs.setText("Mes objectifs :");

        lbObjectifs.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lbObjectifs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btDeconnexion.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btDeconnexion.setText("Déconnexion");

        btAide.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btAide.setText("Aide");

        btAjoutActivite.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btAjoutActivite.setText("Ajout activité");

        btRecapActivite.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btRecapActivite.setText("Recap activités");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btChangerObjectif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAide))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbObjectifs, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbFixeObjectifs)
                                        .addGap(332, 332, 332)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btAjoutActivite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btDeconnexion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btProfil, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btRecapActivite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbMenuPrincipal)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAide)
                    .addComponent(btChangerObjectif))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAjoutActivite)
                    .addComponent(lbFixeObjectifs))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btRecapActivite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btProfil)
                        .addGap(18, 18, 18)
                        .addComponent(btDeconnexion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbObjectifs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAide;
    private javax.swing.JButton btAjoutActivite;
    private javax.swing.JButton btChangerObjectif;
    private javax.swing.JButton btDeconnexion;
    private javax.swing.JButton btProfil;
    private javax.swing.JButton btRecapActivite;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFixeObjectifs;
    private javax.swing.JLabel lbMenuPrincipal;
    private javax.swing.JLabel lbObjectifs;
    // End of variables declaration//GEN-END:variables
}
